name: Generate frozen requirements

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: tag of the Scilpy release
        required: true
        type: string
      python_version:
        description: version for the python interpreter
        required: true
        type: string

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      -
        name: Setup python for Scilpy
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      -
        name: Checkout Scilpy repository
        uses: actions/checkout@v3
        with:
          repository: scilus/scilpy
          ref: ${{ inputs.release_tag }}
      -
        name: Install Scilpy and freeze requirements
        id: requirements
        run: |
          python${{ inputs.python_version }} -m pip install -e .
          python${{ inputs.python_version }} -m pip freeze > requirements.frozen
          echo "requirements-file=$PWD/requirements.frozen" >> $GITHUB_OUTPUT
      -
        name: Checkout this repository
        uses: actions/checkout@v3
        with:
          ref: main
      - 
        name: Create branch for requirements file
        run: |
          git checkout -b scilpy-${{ inputs.release_tag }}-py-${{ inputs.python_version }}
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          mv ${{ steps.requirements.outputs.requirements-file }} requirements.frozen
          git add requirements.frozen
          git commit --message "Generated frozen requirements for Scilpy ${{ inputs.release_tag }} | Python : ${{ inputs.python_version }}"
          git push origin scilpy-${{ inputs.release_tag }}-py-${{ inputs.python_version }}
      - 
        name: Generate release tag associated to the branch
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.release_tag }}-py-${{ inputs.python_version }}
          target_commitish: scilpy-${{ inputs.release_tag }}-py-${{ inputs.python_version }}
      -
        name: Upload requirement file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: requirements
          path: ${{ steps.requirements.outputs.requirements-file }}

